const assert=require('node:assert/strict');
const {BattleModel}=require('../.battle-test-temp/game/battle/BattleModel.js');
const {roadBoundsAt,battleConfig}=require('../.battle-test-temp/game/battle/config.js');
const {settle,doubleCoins}=require('../.battle-test-temp/game/battle/ProgressStore.js');
const {RewardsService}=require('../.battle-test-temp/services/RewardsService.js');
const {upgradeCost}=require('../.battle-test-temp/game/config/economy.js');
const base={level:1,unitIndex:0,weaponIndex:0,unitLevel:1,weaponLevel:1};
assert.equal(upgradeCost(1,0),1040,'First upgrade keeps the 30% price increase');
assert.equal(upgradeCost(1,1),2000,'Second unit/weapon upgrade starts at 2000 coins');
assert.equal(upgradeCost(1,2),4500,'Third unit/weapon upgrade starts at 4500 coins');
assert.equal(Math.round(battleConfig({...base,unitIndex:1}).unit.damage),Math.round(94*.65*2*1.3),'Runner damage includes the requested +80 base damage and speed bonus');
assert.equal(RewardsService.battleCoins(2,0),Math.round(RewardsService.battleCoins(1,0)*1.1),'Each next level must award 10% more coins');
function run(level,strategy){const model=new BattleModel({...base,level},'test-'+level);for(let tick=0;tick<3301&&!model.result;tick++){strategy(model,tick);model.update(1/30)}return model}
const good=run(1,m=>m.moveCannon(195));assert.equal(good.result?.result,'victory','Level 1 must be winnable');assert.equal(good.baseHp,0,'Victory requires fortress destruction');
const bad=run(1,m=>m.moveCannon(287));assert.ok(bad.result,'Battle must finish without portals');
const first=new BattleModel(base,'gates');const cannonRoad=roadBoundsAt(680);first.moveCannon(-100);assert.equal(first.cannonX,cannonRoad.min+10);first.moveCannon(1000);assert.equal(first.cannonX,cannonRoad.max-10);
const unitBounds=new BattleModel(base,'unit-bounds');const spawnRoad=roadBoundsAt(200);assert.equal(unitBounds.spawn('red',-100,200)?.x,spawnRoad.min+10);assert.equal(unitBounds.spawn('red',1000,200)?.x,spawnRoad.max-10);
const isolated=new BattleModel(base,'no-portals');assert.equal(isolated.snapshot().army,2,'Initial player squad is reduced');assert.equal(isolated.snapshot().enemies,11,'Initial enemy wave is reduced by 30%');for(let tick=0;tick<300;tick++)isolated.update(1/30);assert.notEqual(isolated.snapshot().phase,'CHOOSE A PORTAL','No portal phase may appear');assert.equal(isolated.checkpoint().gates,undefined,'New checkpoints contain no portals');
const baseAttacker=new BattleModel({...base,weaponIndex:0},'base-attacker');const attacker=baseAttacker.spawn('red',300,650,'tank');const playerHpBefore=baseAttacker.snapshot().playerHp;for(let tick=0;tick<120;tick++)baseAttacker.update(1/30);assert.ok(attacker?.active,'An enemy at the player base must remain present while attacking');assert.ok(baseAttacker.snapshot().playerHp<playerHpBefore,'An enemy at the player base must damage the player base over time');
const closeTargetModel=new BattleModel({...base,weaponIndex:0},'close-target');const closeTarget=closeTargetModel.spawn('red',300,650,'basic');for(let tick=0;tick<240&&!closeTargetModel.result;tick++)closeTargetModel.update(1/30);assert.equal(closeTarget?.active,false,'The weapon must be able to hit an enemy that is already close to the player base');
assert.equal(first.useBooster('blast'),true);assert.equal(first.useBooster('blast'),false);first.result=bad.result;assert.equal(first.useBooster('freeze'),false);
let journal={version:1,progress:{coins:0,gems:0,level:1,wins:0},receipts:[]};journal=settle(journal,good.result);assert.equal(journal.receipts[0].coins,Math.round(RewardsService.battleCoins(good.result.level,good.result.stars)*.95),'Victory coins are reduced by 5%');assert.equal(journal.progress.level,2);assert.equal(settle(journal,good.result),journal,'Duplicate completion must be ignored');const replay=settle(journal,{...good.result,id:'replay'});assert.equal(replay.progress.level,2);assert.equal(replay.progress.wins,2);const doubled=doubleCoins(journal,good.result.id);assert.equal(doubled.progress.gems,journal.progress.gems);assert.equal(doubleCoins(doubled,good.result.id),doubled);assert.equal(settle(journal,bad.result).progress.coins,journal.progress.coins);
const replayReceipt=replay.receipts.find(r=>r.id==='replay');assert.equal(replayReceipt?.replay,true,'Completed levels must be marked as replays');assert.equal(replayReceipt?.coins,Math.round(journal.receipts[0].coins*.7),'Replay coins must be 70% of the first-clear reward');assert.equal(replayReceipt?.gems,journal.receipts[0].gems,'Replay gems must not be reduced');
for(const level of [3,10,11]){const model=run(level,m=>m.moveCannon(287));assert.ok(model.result);assert.ok(model.units.length===280);assert.ok(model.units.every(u=>Number.isFinite(u.hp)&&Number.isFinite(u.x)));console.log('Level',level,model.result.result,model.result.seconds+'s')}
const fallen=new BattleModel({...base,level:3},'fallen');fallen.playerHp=1;fallen.config.shotInterval=9999;for(const unit of fallen.units)if(unit.team==='blue')unit.active=false;fallen.blueCount=0;for(let tick=0;tick<3301&&!fallen.result;tick++)fallen.update(1/30);assert.equal(fallen.result?.result,'defeat','Revive fixture must reach defeat');const saved=fallen.checkpoint();const revived=new BattleModel({...base,level:3},'revived',()=>{},saved);assert.equal(revived.result,null,'Revived battle must be active');assert.equal(revived.baseHp,saved.baseHp,'Revive must preserve fortress damage');assert.equal(revived.kills,saved.kills,'Revive must preserve kills');assert.equal(revived.playerHp,50,'Revive must restore half shield');assert.ok(revived.time<=saved.time&&revived.time>=saved.time-30,'Revive must preserve progress and leave a continuation window');revived.update(1/30);assert.equal(revived.result,null,'Revive must not instantly defeat the player again');
console.log('PASS: victory, defeat, revive checkpoint, bounds, reduced squads, no portals, boosters, replay, reward idempotency, x2 coins, pool limits.');console.log('Level 1:',good.result.seconds+'s center route;',bad.result.seconds+'s side route');
